name: CI - Shipping

on:
  workflow_dispatch:  # allows manual trigger via gh CLI or GitHub UI
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  ci:
    uses: aartidevops/roboshop-workflows/.github/workflows/ci-reusable.yml@main
    with:
      service_name: shipping
      acr_name: roboshopdevacr
      language: java
      deploy_uat: true
      deploy_prod: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
